
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

import sys
from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\PC\Downloads\Tkinter-Designer-master\Tkinter-Designer-master\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("950x650")
window.configure(bg = "#121212")


canvas = Canvas(
    window,
    bg = "#121212",
    height = 650,
    width = 950,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    395.0,
    0.0,
    anchor="nw",
    text="CONFIGURAÇÃO",
    fill="#FFFFFF",
    font=("Inter", 20 * -1)
)

canvas.create_text(
    7.0,
    70.0,
    anchor="nw",
    text="modo escuro",
    fill="#FFFFFF",
    font=("Inter", 20 * -1)
)

yes = PhotoImage(file="C:\\Users\\PC\\Downloads\\pythorn\\options\\assets\\frame0\\yes.png")
button_1 = Button(
    image=yes,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=550.0,
    y=70.0,
    width=50.0,
    height=25.0
)

no = PhotoImage(file="C:\\Users\\PC\\Downloads\\pythorn\\options\\assets\\frame0\\no.png")
button_2 = Button(
    image=no,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=661.0,
    y=70.0,
    width=50.0,
    height=25.0
)

sair = PhotoImage(file="C:\\Users\\PC\\Downloads\\pythorn\\options\\assets\\frame0\\sair.png")
button_3 = Button(
    image=sair,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: sys.exit(),
    relief="flat"
)
button_3.place(
    x=424.0,
    y=596.0,
    width=102.0,
    height=29.0
)

report = PhotoImage(file="C:\\Users\\PC\\Downloads\\pythorn\\options\\assets\\frame0\\report.png")
button_4 = Button(
    image=report,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=7.0,
    y=241.0,
    width=98.0,
    height=22.0
)
window.resizable(False, False)
window.mainloop()
